# Generated by Django 5.2 on 2025-05-06 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_employee_phone_number_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='ratioofproduct',
            name='ratio',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
