# Generated by Django 5.2 on 2025-05-07 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productionorder_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderdetail',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionorderdetail',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.productionorder'),
        ),
        migrations.AlterField(
            model_name='productionorderdetail',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
