# Generated by Django 5.2 on 2025-05-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_salesorder_client_status_salesorder_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salesorder'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='client_status',
            field=models.CharField(choices=[('تام', 'completed'), ('pending', 'قيد الانتظار'), ('rejected', 'رفض'), ('pending_confirmation', 'جاري التأكيد'), ('confirmed', 'تم التأكد')], default='pending', max_length=20),
        ),
    ]
