# Generated by Django 5.2 on 2025-05-12 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productionorder_sales_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits and start with 01', regex='^01[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionorderdetail',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending', to='core.productionorder'),
        ),
        migrations.AlterField(
            model_name='productionorderdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='client_status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('rejected', 'رفض'), ('confirmed', 'تم التأكد')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('Watingto_Delivered', 'watingto_delivered'), ('Received', 'received')], default='pending', max_length=20),
        ),
    ]
