# Generated by Django 5.2 on 2025-05-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorderdetail',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.productionorder'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('Deliverd', 'deliverd')], default='pending', max_length=20),
        ),
    ]
