# Generated by Django 5.2.3 on 2025-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_salesorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('purchase', 'Purchase'), ('sales', 'Sales'), ('production', 'Production')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionorderdetail',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='client_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('Received', 'Received')], default='pending', max_length=20),
        ),
    ]
