# Generated by Django 5.2.3 on 2025-06-12 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='lower_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
